import macros, tables, os, strutils

const VERSION = "1.0.0"

## .. include:: readme.tmp
# generated by `make` using README.md

const
    TYPE_NAME            = "Options"
    TYPE_PRESENT_NAME    = "Options_Present"
    VAR_NAME             = "options"
    VAR_PRESENT_NAME     = "options_present"
    OFFSET_NAMES_NAME    = "param_names"
    OFFSET_NAME          = "param_offset"
    OFFSET_PRESENT_NAME  = "param_present_offset"
    VAR_TYPE_NAME        = "param_type"
    VAR_DEFAULT_NAME     = "param_defaults"
    VAR_LEN_NAME         = "param_lengths"
    VAR_DESCRIPTION_NAME = "param_descriptions"
    VAR_BARE_NAME        = "param_bare_indexes"
    VAR_REQUIRED_NAME    = "param_requried"
    VAR_ALIAS_NAME       = "param_alias_names"
    VAR_ALIAS_INDEX      = "param_alias_indexes"
    PROC_NAME            = "parse"
    EXE_NAME             = "exe_name"

when isMainModule:
    const DEBUG = true
else:
    const DEBUG = false

var
    dash_denotes_param = true
    slash_denotes_param = true
    use_double_dash = false
    double_dash_separator = false
    split_on_colon = false
    split_on_equals = false
    implicit_bare = true
    quit_on_error = true
    automatic_help = true
    parameters_are_unique = true
    bare_can_still_be_named = false
    program_name = ""
    help_text_pre = ""
    help_text_post = ""


macro config*(body: untyped): untyped =
    ## Helper macro to let you easily specify several config options.
    ##
    ## Example:
    ##
    ## `simple_parseopt.config: no_slash.dash_dash_parameters.allow_repetition`
    ##

    proc check_for_help_text(node: Nim_Node): Nim_Node =
        if node.kind == nnk_ident and (node.str_val == "help_text" or node.str_val == "command_name"):
            return node
        elif node.len > 0:
            for child in node.children:
                var help_node = check_for_help_text(child)
                if help_node != nil:
                    return help_node
        return nil

    let help_node = check_for_help_text(body)
    if help_node != nil:
        error("Cannot include `help_text` or `command_name` in config chain", help_node)

    body.expect_kind(nnk_stmt_list)
    if body.len != 1: error("Expected dot expression", body)

    result = new_nim_node(nnk_stmt_list)
    if body[0].kind == nnk_ident:
        result.add nnk_call.new_tree(body[0].copy_nim_node)
    else:
        body[0].expect_kind(nnk_dot_expr)
        proc walk(node: Nim_Node, write: Nim_Node, count = 0) =
            if node.len == 2 and node[1].kind == nnk_ident:
                if node[0].kind == nnk_dot_expr:
                    walk(node[0], write, count+1)
                    write.add nnk_call.new_tree(node[1].copy_nim_node)
                elif node[0].kind == nnk_ident:
                    write.add nnk_call.new_tree(node[0].copy_nim_node)
                    write.add nnk_call.new_tree(node[1].copy_nim_node)
                else:
                    error("Expected dot expression", node)
            else:
                error("Expected dot expression", node)
        walk body[0], result


proc no_dash*() =
    ## Disable parameter being identified by prefixing with `-`
    dash_denotes_param = false

proc no_slash*() =
    ## Disable parameter being identified by prefixing with `/`
    slash_denotes_param = false

proc dash_dash_parameters*() =
    ## Require that parameters which have more than one character in their name
    ## be prefixed with `--` instead of `-`.
    ##
    ## Single-character parameters may then be entered grouped together under
    ## one `-`
    use_double_dash = true

proc dash_dash_separator*() =
    ## `--` on its own in the command line will disable parameter names on every
    ## argument after it; they will all be treated as bare.
    double_dash_separator = true

proc value_after_colon*() =
    ## Allow the user to specify parameter & value together, separated by a `:`
    ##
    ## e.g. `-param:value`
    ##
    ## Note this will not play nicely with quoted string values.
    split_on_colon = true

proc value_after_equals*() =
    ## Allow the user to specify parameter & value together, separated by a `=`
    ##
    ## e.g. `-param=value`
    ##
    ## Note this will not play nicely with quoted string values.
    split_on_equals = true

proc allow_repetition*() =
    ## Allow the user to specify the same parameter more than once without
    ## reporting an error.
    parameters_are_unique = false

proc allow_errors*() =
    ## Allow program execution to continue after erroneous input.
    quit_on_error = true

proc no_implicit_bare*() =
    ## Do not automatically use the last `seq[string]` parameter to gather any
    ## bare parameters the user enters (instead they become erroneous)
    implicit_bare = false

proc can_name_bare*() =
    ## Allows user to set bare parameters by name.
    bare_can_still_be_named = true

proc manual_help*() =
    ## Disable automatic generation of help message when user enters
    ## `-?`, `-h` or `-help` (when you do not include them as parameters)
    automatic_help = false


proc command_name*(name: string) =
    ## Set the name of the executable, for use in the auto-generated
    ## help-message when the user enters `-?`, `-h`, or `-help`.
    ##
    ## Note: `command_name` may not be included in a `config:` chain
    program_name = name

proc help_text*(text, footer = "") =
    ## Set the text which is included in the auto-generated help-message
    ## when the user enters `-?`, `-h`, or `-help`.
    ##
    ## `text` is displayed at the top, before the parameters.
    ## `footer` is displayed at the bottom, after them.
    ##
    ## Note: `help_text` may not be included in a `config:` chain
    help_text_pre = text
    help_text_post = footer


template print(s: string) =
    echo s

when DEBUG:
    var DEBUG_ARGS = ""
    proc prettify[T](title: string, data: T, new_section = false) =
        if new_section:
            print "--------------"
        print title
        let s = $data
        var indenting = false
        for output in s[1 ..< ^1].strip.replace("[", "").replace("]", "").split(','):
            var line = output.strip()
            if line.ends_with("\"") and " = 0" in line:
                let start = line.find(" = 0")
                let skip = line.find("\"")
                line = line[0 ..< start + 3] & line[skip ..< ^0]
            if line.contains(": @"):
                let c = line.find("@")
                print line[0 ..< c]
                line = line[c + 1 ..< ^0]
                indenting = true
            if indenting:
                if line.contains(":"):
                    indenting = false
                else:
                    line = "  " & line
            if line != "":
                print line
        print ""


type Param_Kind = enum
    param_undefined,
    param_int,
    param_i8,
    param_i16,
    param_i32,
    param_i64,
    param_uint,
    param_u8,
    param_u16,
    param_u32,
    param_u64,
    param_float,
    param_f32,
    param_f64,
    param_char,
    param_string,
    param_bool,
    param_seq_string,
    param_seq_int,
    param_seq_float,


const
    int_param_undefined  = 0
    int_param_int        = 1
    int_param_i8         = 2
    int_param_i16        = 3
    int_param_i32        = 4
    int_param_i64        = 5
    int_param_uint       = 6
    int_param_u8         = 7
    int_param_u16        = 8
    int_param_u32        = 9
    int_param_u64        = 10
    int_param_float      = 11
    int_param_f32        = 12
    int_param_f64        = 13
    int_param_char       = 14
    int_param_string     = 15
    int_param_bool       = 16
    int_param_seq_string = 17
    int_param_seq_int    = 18
    int_param_seq_float  = 19


type Param = object
    name: string
    accepts_bare: bool
    description: string
    alias: seq[string]
    required: bool
    seq_len: int
    case kind: ParamKind
    of param_undefined:    discard
    of param_int:          int_value: int
    of param_i8:           i8_value: int8
    of param_i16:          i16_value: int16
    of param_i32:          i32_value: int32
    of param_i64:          i64_value: int64
    of param_uint:         uint_value: uint
    of param_u8:           u8_value: uint8
    of param_u16:          u16_value: uint16
    of param_u32:          u32_value: uint32
    of param_u64:          u64_value: uint64
    of param_float:        float_value: float
    of param_f32:          f32_value: float32
    of param_f64:          f64_value: float64
    of param_char:         char_value: char
    of param_string:       string_value: string
    of param_bool:         bool_value: bool
    of param_seq_string:   seq_string_value: seq[string]
    of param_seq_int:      seq_int_value: seq[int]
    of param_seq_float:    seq_float_value: seq[float]


proc int_param_from_param(kind: Param_Kind): int =
    case kind:
    of param_undefined:  return int_param_undefined
    of param_int:        return int_param_int
    of param_i8:         return int_param_i8
    of param_i16:        return int_param_i16
    of param_i32:        return int_param_i32
    of param_i64:        return int_param_i64
    of param_uint:       return int_param_uint
    of param_u8:         return int_param_u8
    of param_u16:        return int_param_u16
    of param_u32:        return int_param_u32
    of param_u64:        return int_param_u64
    of param_float:      return int_param_float
    of param_f32:        return int_param_f32
    of param_f64:        return int_param_f64
    of param_char:       return int_param_char
    of param_string:     return int_param_string
    of param_bool:       return int_param_bool
    of param_seq_string: return int_param_seq_string
    of param_seq_int:    return int_param_seq_int
    of param_seq_float:  return int_param_seq_float


proc param_from_nodes(name_node: Nim_Node, kind: Param_Kind, value_node: Nim_Node, pragma_node: Nim_Node): (Param, string) =
    let name = name_node.str_val.to_lower
    var param: Param
    if value_node == nil:
        case kind:
            of param_undefined:  param = Param(name: name, kind: param_undefined)
            of param_int:        param = Param(name: name, kind: param_int)
            of param_i8:         param = Param(name: name, kind: param_i8)
            of param_i16:        param = Param(name: name, kind: param_i16)
            of param_i32:        param = Param(name: name, kind: param_i32)
            of param_i64:        param = Param(name: name, kind: param_i64)
            of param_uint:       param = Param(name: name, kind: param_uint)
            of param_u8:         param = Param(name: name, kind: param_u8)
            of param_u16:        param = Param(name: name, kind: param_u16)
            of param_u32:        param = Param(name: name, kind: param_u32)
            of param_u64:        param = Param(name: name, kind: param_u64)
            of param_float:      param = Param(name: name, kind: param_float)
            of param_f32:        param = Param(name: name, kind: param_f32)
            of param_f64:        param = Param(name: name, kind: param_f64)
            of param_char:       param = Param(name: name, kind: param_char)
            of param_string:     param = Param(name: name, kind: param_string)
            of param_bool:       param = Param(name: name, kind: param_bool)
            of param_seq_string: param = Param(name: name, kind: param_seq_string)
            of param_seq_int:    param = Param(name: name, kind: param_seq_int)
            of param_seqfloat:   param = Param(name: name, kind: param_seq_float)
    else:
        case kind:
        of param_undefined:  param = Param(name: name, kind: param_undefined)
        of param_int:        param = Param(name: name, kind: param_int,        int_value:        cast[int](value_node.int_val))
        of param_i8:         param = Param(name: name, kind: param_i8,         i8_value:         cast[int8](value_node.int_val))
        of param_i16:        param = Param(name: name, kind: param_i16,        i16_value:        cast[int16](value_node.int_val))
        of param_i32:        param = Param(name: name, kind: param_i32,        i32_value:        cast[int32](value_node.int_val))
        of param_i64:        param = Param(name: name, kind: param_i64,        i64_value:        value_node.int_val)
        of param_uint:       param = Param(name: name, kind: param_uint,       uint_value:       cast[uint](value_node.int_val))
        of param_u8:         param = Param(name: name, kind: param_u8,         u8_value:         cast[uint8](value_node.int_val))
        of param_u16:        param = Param(name: name, kind: param_u16,        u16_value:        cast[uint16](value_node.int_val))
        of param_u32:        param = Param(name: name, kind: param_u32,        u32_value:        cast[uint32](value_node.int_val))
        of param_u64:        param = Param(name: name, kind: param_u64,        u64_value:        cast[uint64](value_node.int_val))
        of param_float:      param = Param(name: name, kind: param_float,      float_value:      value_node.float_val)
        of param_f32:        param = Param(name: name, kind: param_f32,        f32_value:        value_node.float_val)
        of param_f64:        param = Param(name: name, kind: param_f64,        f64_value:        value_node.float_val)
        of param_char:       param = Param(name: name, kind: param_char,       char_value:       cast[char](value_node.int_val))
        of param_string:     param = Param(name: name, kind: param_string,     string_value:     value_node.str_val)
        of param_bool:       param = Param(name: name, kind: param_bool,       bool_value:       value_node.str_val == "true")
        of param_seq_string: param = Param(name: name, kind: param_seq_string, seq_string_value: @[])
        of param_seq_int:    param = Param(name: name, kind: param_seq_int,    seq_int_value:    @[])
        of param_seq_float:  param = Param(name: name, kind: param_seq_float,  seq_float_value:  @[])

    if pragma_node != nil:
        if pragma_node.kind == nnk_ident:
            if pragma_node.str_val == "bare" or pragma_node.str_val == "positional":
                param.accepts_bare = true
            elif pragma_node.str_val == "need" or pragma_node.str_val == "required":
                param.required = true
            else:
                error("invalid pragma", pragma_node)
        else:
            for child in pragma_node.children:
                if child.kind == nnk_ident:
                    if child.str_val == "bare" or child.str_val == "positional":
                        param.accepts_bare = true
                    elif child.str_val == "need" or child.str_val == "required":
                        param.required = true
                    else:
                        error("invalid pragma", child)
                elif child.kind != nnk_call or len(child) < 2 or child[0].kind != nnk_ident:
                    error("invalid pragma", child)
                elif child[0].str_val == "aka" or child[0].str_val == "alias":
                    if child[0].kind != nnk_ident or child.len < 2:
                        error("invalid pragma", child)
                    param.alias = @[]
                    for i in 1 ..< child.len:
                        let alias = child[i]
                        if alias.kind != nnk_str_lit:
                            error("invalid pragma", alias)
                        else:
                            param.alias.add alias.str_val
                elif child[0].str_val == "info" or child[0].str_val == "description":
                    if child[1].kind != nnk_str_lit:
                        error("invalid pragma", child[1])
                    else:
                        param.description = child[1].str_val
                elif child[0].str_val == "len" or child[0].str_val == "count":
                    if child[1].kind != nnk_int_lit:
                        error("invalid pragma", child[1])
                    else:
                        param.seq_len = cast[int](child[1].int_val)
                else:
                    error("invalid pragma", pragma_node)

    return (param, name)


proc kind_from_lit(lit: Nim_Node): Param_Kind =
    case lit.kind
    of nnk_int_lit:
        return param_int
    of nnk_float_lit:
        return param_float
    of nnk_char_lit:
        return param_char
    of nnk_str_lit:
        return param_string
    of nnk_ident:
        if lit.str_val == "true" or lit.str_val == "false":
            return param_bool
        else:
            return param_undefined
    else:
        return param_undefined


proc ident_from_kind(kind: Param_Kind): Nim_Node =
    case kind
    of param_undefined:    return nil
    of param_seq_string:   return nnk_bracket_expr.new_tree(ident("seq"), ident("string"))
    of param_seq_int:      return nnk_bracket_expr.new_tree(ident("seq"), ident("int"))
    of param_seq_float:    return nnk_bracket_expr.new_tree(ident("seq"), ident("float"))
    of param_int:          return ident("int")
    of param_i8:           return ident("int8")
    of param_i16:          return ident("int16")
    of param_i32:          return ident("int32")
    of param_i64:          return ident("int64")
    of param_uint:         return ident("uint")
    of param_u8:           return ident("uint8")
    of param_u16:          return ident("uint16")
    of param_u32:          return ident("uint32")
    of param_u64:          return ident("uint64")
    of param_float:        return ident("float")
    of param_f32:          return ident("float32")
    of param_f64:          return ident("float64")
    of param_char:         return ident("char")
    of param_string:       return ident("string")
    of param_bool:         return ident("bool")


proc kind_from_ident(ident: Nim_node): Param_Kind =
    if ident.kind == nnk_dot_expr and ident.len == 2 and
            ident[0].kind == nnk_ident and ident[0].str_val == "seq" and
            ident[1].kind == nnk_ident:
        case ident[1].str_val:
        of "string":    return param_seq_string
        of "int":       return param_seq_int
        of "float":     return param_seq_float
        else:           return param_undefined
    else:
        case ident.str_val
        of "int":       return param_int
        of "int8":      return param_i8
        of "int16":     return param_i16
        of "int32":     return param_i32
        of "int64":     return param_i64
        of "uint":      return param_uint
        of "uint8":     return param_u8
        of "uint16":    return param_u16
        of "uint32":    return param_u32
        of "uint64":    return param_u64
        of "float":     return param_float
        of "float32":   return param_f32
        of "float64":   return param_f64
        of "char":      return param_char
        of "string":    return param_string
        of "true":      return param_bool
        of "false":     return param_bool
        else:           return param_undefined

proc seq_kind_from_ident(ident: Nim_node): Param_Kind =
    case ident.str_val
    of "string":    return param_seq_string
    of "int":       return param_seq_int
    of "float":     return param_seq_float
    else:           return param_undefined

proc value_node_from_param(param: Param): Nim_Node =
    case param.kind:
    of param_undefined:  return nil
    of param_seq_string: return nil
    of param_seq_int:    return nil
    of param_seq_float:  return nil
    of param_int:        return new_int_lit_node(param.int_value)
    of param_i8:         return new_int_lit_node(param.i8_value)
    of param_i16:        return new_int_lit_node(param.i16_value)
    of param_i32:        return new_int_lit_node(param.i32_value)
    of param_i64:        return new_int_lit_node(param.i64_value)
    of param_uint:       return new_int_lit_node(cast[Biggest_Int](param.uint_value))
    of param_u8:         return new_int_lit_node(cast[Biggest_Int](param.u8_value))
    of param_u16:        return new_int_lit_node(cast[Biggest_Int](param.u16_value))
    of param_u32:        return new_int_lit_node(cast[Biggest_Int](param.u32_value))
    of param_u64:        return new_int_lit_node(cast[Biggest_Int](param.u64_value))
    of param_float:      return new_float_lit_node(param.float_value)
    of param_f32:        return new_float_lit_node(param.f32_value)
    of param_f64:        return new_float_lit_node(param.f64_value)
    of param_char:       return new_lit(param.char_value)
    of param_string:     return new_str_lit_node(param.string_value)
    of param_bool:
        if param.bool_value:
            return ident("true")
        else:
            return ident("false")


proc string_from_param(param: Param): string =
    case param.kind:
    of param_undefined:  return ""
    of param_seq_string: return ""
    of param_seq_int:    return ""
    of param_seq_float:  return ""
    of param_int:        return repr(param.int_value)
    of param_i8:         return repr(param.i8_value)
    of param_i16:        return repr(param.i16_value)
    of param_i32:        return repr(param.i32_value)
    of param_i64:        return repr(param.i64_value)
    of param_uint:       return repr(param.uint_value)
    of param_u8:         return repr(param.u8_value)
    of param_u16:        return repr(param.u16_value)
    of param_u32:        return repr(param.u32_value)
    of param_u64:        return repr(param.u64_value)
    of param_float:      return repr(param.float_value)
    of param_f32:        return repr(param.f32_value)
    of param_f64:        return repr(param.f64_value)
    of param_char:       return repr(param.char_value)
    of param_string:     return param.string_value
    of param_bool:
        if param.bool_value:
            return "true"
        else:
            return "false"


type Assignment = tuple
    kind: Param_Kind
    name_node: Nim_Node
    value_node: Nim_Node
    pragma_node: Nim_Node
    error: int

proc assignment_from_node(node: Nim_Node): Assignment =
    if node.kind == nnk_asgn: # simple assignment
        if node.len != 2 or node[0].kind != nnk_ident:                                                  # error 1
            return (param_undefined, nil, nil, nil, 1)

        elif node[1].kind == nnk_pragma_expr and len(node[1]) == 2 and node[1][1].kind == nnk_pragma:   # x = n + pragma
            return (kind_from_lit(node[1][0]), node[0], node[1][0], node[1][1], 0)
        else:                                                                                           # x = n
            return (kind_from_lit(node[1]), node[0], node[1], nil, 0)

    elif node.kind == nnk_call: # typed assignment
        if node.len != 2 or node[0].kind != nnk_ident or node[1].kind != nnk_stmt_list:                 # error 2
            return (param_undefined, nil, nil, nil, 2)

        elif node[1].len == 1 and node[1][0].kind == nnk_bracket_expr and node[1][0].len == 2 and       # x:seq[t]
                node[1][0][0].kind == nnk_ident and node[1][0][0].str_val == "seq" and
                node[1][0][1].kind == nnk_ident:
            return (seq_kind_from_ident(node[1][0][1]), node[0], nil, nil, 0)
        elif node[1].len == 1 and node[1][0].kind == nnk_pragma_expr and                                # x:seq[t] + pragma
                node[1][0][0].kind == nnk_bracket_expr and node[1][0][0].len == 2 and
                node[1][0][0][0].kind == nnk_ident and node[1][0][0][0].str_val == "seq" and
                node[1][0][0][1].kind == nnk_ident:
            return (seq_kind_from_ident(node[1][0][0][1]), node[0], nil, node[1][0][1], 0)

        elif node[1].len == 1 and node[1][0].kind == nnk_ident:                                         # x:t
            return (kind_from_ident(node[1][0]), node[0], nil, nil, 0)
        elif node[1].len == 1 and node[1][0].kind == nnk_pragma_expr:                                   # x:t + pragma
            return (kind_from_ident(node[1][0][0]), node[0], nil, node[1][0][1], 0)


        elif node[1].len != 1 or node[1][0].kind != nnk_asgn:                                           # error 3
            return (param_undefined, nil, nil, nil, 3)
        elif node[1][0].len != 2 or node[1][0][0].kind != nnk_ident:                                    # error 4
            return (param_undefined, nil, nil, nil, 4)

        elif node[1][0].len == 2 and node[1][0][1].kind == nnk_pragma_expr:                             # x:t = n + pragma
            return (kind_from_ident(node[1][0][0]), node[0], node[1][0][1][0], node[1][0][1][1], 0)
        else:                                                                                           # x:t = n
            return (kind_from_ident(node[1][0][0]), node[0], node[1][0][1], nil, 0)


macro get_options_and_supplied*(body: untyped): untyped =
    ## Parses the command-line arguments provided by the user,
    ## using it and the code block to fill out an object's fields.
    ##
    ## Returns a tuple of two objects: the first as detailed by
    ## the code block, the second a mirror of it, but all of type `bool`.
    ## For any parameters which the user has supplied on the command line,
    ## the field on the second object will be set to `true`.
    ##
    ##
    ## All basic intrinsic types are supported:
    ## `string`, `char`, `bool`, `int`, `uint`, `float`
    ## (and all size variants: `int16`, `float32`, etc.)
    ##
    ## The block is written as if it were a `var`, i.e. all of these are valid:
    ## ```
    ## x = 0
    ## x:int32
    ## x:int = 20
    ## ```
    ## You may also use `seq[string]`, `seq[int]`, and `seq[float]` (though
    ## these may not be initialized to a default value: they must be empty)
    ## ```
    ## args: seq[string]
    ## ```
    ## If you do not explicitly specify a `{. bare .}` `seq[string]`, but do
    ## have one or more `seq[string]`, then the last one will be used to store
    ## all bare arguments.  (i.e. will be treated as if it had an implicit
    ## `{. bare .}` pragma.)
    ## This may be disabled with the `no_implicit_bare` setting.
    ##
    ##
    ## You may also add pragmas to the end of any line to modify parameter
    ## behaviour.  Each pragma has a more verbose alias, if you prefer that
    ## style of code.
    ##
    ## `{. info("text") .}` or `{. description("text") .}`
    ##   Description of the parameter shown in help text.
    ##
    ##
    ## `{. aka("a", "b", ...) .}` or `{. alias("a", "b", ...) .}`
    ##   Aliases for the parameter - user may use these as parameters;
    ##   they will write to the variable.
    ##
    ##
    ## `{. bare .}` or `{. positional .}`
    ##  Accepts a bare, positional argument (an argument which has not
    ##  been prefixed with a parameter name).  User will not be able to
    ##  refer to the argmuent with its parameter name.
    ##
    ##
    ## `{. need .}` or `.{ required .}`
    ##  Parameter must be supplied by user or an error is shown.
    ##
    ##
    ## `{. len(i) .}` or `.{ count(i) .}`
    ##  Place on a `seq` field to require that many values be supplied to it.
    ##  For example:
    ##  `position:seq[float] {. len(3) .} # x y z`
    ##
    ##
    ## *Example:*
    ## ```
    ## let options, supplied = get_options_and_supplied:
    ##     teenager = "Joe Random" {. aka("name", "n") .}
    ##     age[int8] = 13
    ##     nin:string              {. info("National Insurance Number") .}
    ##     arguments:seq[string]
    ##
    ## if not supplied.nin:
    ##     report "Must supply NIN"
    ##     quit(1)
    ##
    ## if options.age < 13 or options.age > 19:
    ##     report "Not a teenager!"
    ##     quit(1)
    ## ```


    if body.kind != nnk_stmt_list:
        error("Block expected, e.g. var opts = parse_params: ...", body)

    var params = init_table[string, Param]()
    var params_in_order: seq[string] = @[]
    var aliases:seq[string] = @[]

    for node in body.children:
        var (kind, name_node, value_node, pragma_node, error) = assignment_from_node(node)
        if  kind == param_undefined:
            error("Expected declaration, e.g. x = 1 or x:int = 1 or x:int [ERR:" & error.repr & "]", node)
        let (param, name) = param_from_nodes(name_node, kind, value_node, pragma_node)
        for alias in param.alias:
            if alias in params or alias in aliases:
                error("Duplicate parameter: " & alias, node)
            aliases.add alias
        if name in params or name in aliases:
            error("Duplicate parameter: " & name, node)

        params[name] = param
        params_in_order.add(name)

    var param_names_node = new_nim_node(nnk_var_section)
    param_names_node.add(
        nnk_ident_defs.new_tree(
            ident(OFFSET_NAMES_NAME),
            new_empty_node(),
            nnk_call.new_tree(
                nnk_bracket_expr.new_tree(
                    ident("new_seq"),
                    ident("string")))))

    var param_node = new_nim_node(nnk_var_section)
    param_node.add(
        nnk_ident_defs.new_tree(
            ident(OFFSET_NAME),
            new_empty_node(),
            nnk_call.new_tree(
                nnk_bracket_expr.new_tree(
                    ident("new_seq"),
                    ident("uint")))))

    var param_present_node = new_nim_node(nnk_var_section)
    param_present_node.add(
        nnk_ident_defs.new_tree(
            ident(OFFSET_PRESENT_NAME),
            new_empty_node(),
            nnk_call.new_tree(
                nnk_bracket_expr.new_tree(
                    ident("new_seq"),
                    ident("uint")))))

    var param_type_node = new_nim_node(nnk_var_section)
    param_type_node.add(
        nnk_ident_defs.new_tree(
            ident(VAR_TYPE_NAME),
            new_empty_node(),
            nnk_call.new_tree(
                nnk_bracket_expr.new_tree(
                    ident("new_seq"),
                    ident("int")))))

    var param_alias_name_node = new_nim_node(nnk_var_section)
    param_alias_name_node.add(
        nnk_ident_defs.new_tree(
            ident(VAR_ALIAS_NAME),
            new_empty_node(),
            nnk_call.new_tree(
                nnk_bracket_expr.new_tree(
                    ident("new_seq"),
                    ident("string")))))

    var param_alias_index_node = new_nim_node(nnk_var_section)
    param_alias_index_node.add(
        nnk_ident_defs.new_tree(
            ident(VAR_ALIAS_INDEX),
            new_empty_node(),
            nnk_call.new_tree(
                nnk_bracket_expr.new_tree(
                    ident("new_seq"),
                    ident("int")))))

    var param_default_node = new_nim_node(nnk_var_section)
    param_default_node.add(
        nnk_ident_defs.new_tree(
            ident(VAR_DEFAULT_NAME),
            new_empty_node(),
            nnk_call.new_tree(
                nnk_bracket_expr.new_tree(
                    ident("new_seq"),
                    ident("string")))))

    var param_len_node = new_nim_node(nnk_var_section)
    param_len_node.add(
        nnk_ident_defs.new_tree(
            ident(VAR_LEN_NAME),
            new_empty_node(),
            nnk_call.new_tree(
                nnk_bracket_expr.new_tree(
                    ident("new_seq"),
                    ident("int")))))


    var param_description_node = new_nim_node(nnk_var_section)
    param_description_node.add(
        nnk_ident_defs.new_tree(
            ident(VAR_DESCRIPTION_NAME),
            new_empty_node(),
            nnk_call.new_tree(
                nnk_bracket_expr.new_tree(
                    ident("new_seq"),
                    ident("string")))))

    var bare_index_node = new_nim_node(nnk_var_section)
    bare_index_node.add(
        nnk_ident_defs.new_tree(
            ident(VAR_BARE_NAME),
            new_empty_node(),
            nnk_call.new_tree(
                nnk_bracket_expr.new_tree(
                    ident("new_seq"),
                    ident("int")))))

    var param_required_node = new_nim_node(nnk_var_section)
    param_required_node.add(
        nnk_ident_defs.new_tree(
            ident(VAR_REQUIRED_NAME),
            new_empty_node(),
            nnk_call.new_tree(
                nnk_bracket_expr.new_tree(
                    ident("new_seq"),
                    ident("int")))))

    var offset_node = new_nim_node(nnk_block_stmt)
    offset_node.add new_empty_node()
    offset_node.add new_nim_node(nnk_stmt_list)

    let proc_name = ident(PROC_NAME)
    let type_name = ident(TYPE_NAME)
    let present_type_name = ident(TYPE_PRESENT_NAME)
    let outer_param_names = ident(OFFSET_NAMES_NAME)
    let outer_param_offset = ident(OFFSET_NAME)
    let outer_param_present_offset = ident(OFFSET_PRESENT_NAME)
    let outer_param_type = ident(VAR_TYPE_NAME)
    #let outer_param_default = ident(VAR_DEFAULT_NAME)  # Could be used to display defaults in do_help
    let outer_bare_indexes = ident(VAR_BARE_NAME)
    let outer_param_descriptions = ident(VAR_DESCRIPTION_NAME)
    let outer_required_indexes = ident(VAR_REQUIRED_NAME)
    let outer_param_length = ident(VAR_LEN_NAME)
    let outer_alias_names = ident(VAR_ALIAS_NAME)
    let outer_alias_index = ident(VAR_ALIAS_INDEX)
    let outer_exe_name = ident(EXE_NAME)

    var proc_node = quote do:
        proc `proc_name`(options: var `type_name`, present: var `present_type_name`): (`type_name`, `present_type_name`) =

            when DEBUG:
                prettify("Options", options.repr, true)
                prettify("Supplied", present.repr)

            template parse_error(err: string) =
                print err
                if quit_on_error:
                    quit(1)

            proc index_from_name(name: string): int =
                for (i, n) in `outer_param_names`.pairs:
                    if n == name:
                        return i
                for (i, n) in `outer_alias_names`.pairs:
                    if n == name:
                        return `outer_alias_index`[i]
                parse_error("Cannot find option: " & name)

            proc get_param_offset(name: string): uint =
                return `outer_param_offset`[index_from_name(name)]

            proc get_param_present_offset(name: string): uint =
                return `outer_param_present_offset`[index_from_name(name)]

            proc get_param_type(name: string): int =
                return `outer_param_type`[index_from_name(name)]

            proc get_desired_seq_len(name: string): int =
                return `outer_param_length`[index_from_name(name)]

            proc is_bare(index: int): bool =
                `outer_bare_indexes`.contains(index)

            proc is_bare(name: string): bool =
                is_bare(index_from_name(name))

            proc is_seq(name: string): bool =
                let kind = get_param_type(name)
                return kind == int_param_seq_string or kind == int_param_seq_int or kind == int_param_seq_float

            template get_prefix(name: string, index = -1): string =
                if not bare_can_still_be_named and index >= 0 and is_bare(index):
                    ""
                elif not bare_can_still_be_named and index >= 0  and is_bare(name):
                    ""
                elif dash_denotes_param:
                    if use_double_dash and name.len > 1:
                        "--"
                    else:
                        "-"
                elif slash_denotes_param:
                    "/"
                else:
                    ""

            proc do_help() =
                if help_text_pre != "":
                    print help_text_pre

                print ""

                proc full_name(index: int): string =
                    var name = `outer_param_names`[index]
                    if `outer_alias_index`.contains(index):
                        for i, alias_index in `outer_alias_index`.pairs:
                            if alias_index == index:
                                let alias = `outer_alias_names`[i]
                                name = name & ", " & get_prefix(alias, index) & alias
                    return name

                var added_options = false
                var usage:string
                if program_name != "":
                    usage = program_name
                else:
                    usage = `outer_exe_name`
                for i, name in `outer_param_names`:
                    if is_bare(i):
                        if `outer_required_indexes`.contains(i):
                            usage &= " " & name
                        else:
                            usage &= " [" & name & "]"
                    else:
                        if `outer_required_indexes`.contains(i):
                            usage &= " " & get_prefix(name) & name
                            if `outer_param_type`[i] != `int_param_bool`:
                                usage &= " " & "<value>"
                        elif not added_options:
                            usage &= " " & "[options]"
                            added_options = true

                print " " & usage
                print ""

                var letters = 0
                for i, _ in `outer_param_names`:
                    let name = full_name(i)
                    if name.len > letters: letters = name.len

                var printed_header = false

                for i, name in `outer_param_names`:
                    if not is_bare(i): continue
                    if not printed_header:
                        print "Arguments:"
                        print ""
                        printed_header = true
                    let postfix = `outer_param_descriptions`[i]
                    if postfix == "":
                        print " " & name
                    else:
                        var spacer = ""
                        while name.len + spacer.len < letters:
                            spacer = spacer & " "
                        print " " & name & spacer & "    " & postfix
                if printed_header: print ""

                printed_header = false

                for i, name in `outer_param_names`:
                    if is_bare(i): continue
                    if not printed_header:
                        print "Options:"
                        print ""
                        printed_header = true
                    let display_name = full_name(i)
                    let postfix = `outer_param_descriptions`[i]
                    if postfix == "":
                        print " " & get_prefix(name) & display_name
                    else:
                        var spacer = ""
                        while display_name.len + spacer.len < letters:
                            spacer = spacer & " "
                        print " " & get_prefix(name) & display_name & spacer & "    " & postfix
                if printed_header: print ""

                if help_text_post != "":
                    print help_text_post
                    print ""


            proc is_present(address: ptr `present_type_name`, name: string): bool =
                let field = cast[ptr bool](cast[uint](address) + get_param_present_offset(name))
                return field[]

            proc set_present(address: ptr `present_type_name`, name: string) =
                let field = cast[ptr bool](cast[uint](address) + get_param_present_offset(name))
                field[] = true

            proc int_from_string[T](s: string): (T, bool) =
                try:
                    result = (cast[T](parse_biggest_int(s)), true)
                except:
                    return (cast[T](0), false)

            proc uint_from_string[T](s: string): (T, bool) =
                try:
                    result = (cast[T](parse_biggest_uint(s)), true)
                except:
                    return (cast[T](0), false)

            proc float_from_string[T](s: string): (T, bool) =
                try:
                    result = (cast[T](parse_float(s)), true)
                except:
                    return (cast[T](0), false)

            proc get_seq_len(address: ptr `type_name`, name: string, kind: int): int =
                case kind
                of `int_param_seq_string`:
                    let field = cast[ptr seq[string]](cast[uint](address) + get_param_offset(name))
                    return field[].len
                of `int_param_seq_int`:
                    let field = cast[ptr seq[int]](cast[uint](address) + get_param_offset(name))
                    return field[].len
                of `int_param_seq_float`:
                    let field = cast[ptr seq[float]](cast[uint](address) + get_param_offset(name))
                    return field[].len
                else:
                    return 0

            proc can_parse_as(value: string, kind: int): bool =
                case kind
                of `int_param_string`:
                    return true
                of `int_param_bool`:
                    return false
                of `int_param_int`:
                    return int_from_string[int](value)[1]
                of `int_param_i8`:
                    return int_from_string[int](value)[1]
                of `int_param_i16`:
                    return int_from_string[int](value)[1]
                of `int_param_i32`:
                    return int_from_string[int](value)[1]
                of `int_param_i64`:
                    return int_from_string[int](value)[1]
                of `int_param_uint`:
                    return uint_from_string[int](value)[1]
                of `int_param_u8`:
                    return uint_from_string[int](value)[1]
                of `int_param_u16`:
                    return uint_from_string[int](value)[1]
                of `int_param_u32`:
                    return uint_from_string[int](value)[1]
                of `int_param_u64`:
                    return uint_from_string[int](value)[1]
                of `int_param_float`:
                    return float_from_string[int](value)[1]
                of `int_param_f32`:
                    return float_from_string[int](value)[1]
                of `int_param_f64`:
                    return float_from_string[int](value)[1]
                of `int_param_char`:
                    return value.len == 1
                of `int_param_undefined`:
                    return false
                of `int_param_seq_string`:
                    return true
                of `int_param_seq_float`:
                    return float_from_string[int](value)[1]
                of `int_param_seq_int`:
                    return int_from_string[int](value)[1]
                else:
                    return false


            proc set_value(address: ptr `type_name`, name: string, value: string = ""): bool =
                let kind = get_param_type(name)
                case kind
                of `int_param_string`:
                    let field = cast[ptr string](cast[uint](address) + get_param_offset(name))
                    field[] = value
                    return true
                of `int_param_bool`:
                    let field = cast[ptr bool](cast[uint](address) + get_param_offset(name))
                    field[] = not field[]
                    return true
                of `int_param_int`:
                    let (parsed_value, success) = int_from_string[int](value)
                    if success:
                        let field = cast[ptr int](cast[uint](address) + get_param_offset(name))
                        field[] = parsed_value
                    return success
                of `int_param_i8`:
                    let (parsed_value, success) = int_from_string[int8](value)
                    if success:
                        let field = cast[ptr int8](cast[uint](address) + get_param_offset(name))
                        field[] = parsed_value
                    return success
                of `int_param_i16`:
                    let (parsed_value, success) = int_from_string[int16](value)
                    if success:
                        let field = cast[ptr int16](cast[uint](address) + get_param_offset(name))
                        field[] = parsed_value
                    return success
                of `int_param_i32`:
                    let (parsed_value, success) = int_from_string[int32](value)
                    if success:
                        let field = cast[ptr int32](cast[uint](address) + get_param_offset(name))
                        field[] = parsed_value
                    return success
                of `int_param_i64`:
                    let (parsed_value, success) = int_from_string[int64](value)
                    if success:
                        let field = cast[ptr int64](cast[uint](address) + get_param_offset(name))
                        field[] = parsed_value
                    return success
                of `int_param_uint`:
                    let (parsed_value, success) = uint_from_string[uint](value)
                    if success:
                        let field = cast[ptr uint](cast[uint](address) + get_param_offset(name))
                        field[] = parsed_value
                    return success
                of `int_param_u8`:
                    let (parsed_value, success) = uint_from_string[uint8](value)
                    if success:
                        let field = cast[ptr uint8](cast[uint](address) + get_param_offset(name))
                        field[] = parsed_value
                    return success
                of `int_param_u16`:
                    let (parsed_value, success) = uint_from_string[uint16](value)
                    if success:
                        let field = cast[ptr uint16](cast[uint](address) + get_param_offset(name))
                        field[] = parsed_value
                    return success
                of `int_param_u32`:
                    let (parsed_value, success) = uint_from_string[uint32](value)
                    if success:
                        let field = cast[ptr uint32](cast[uint](address) + get_param_offset(name))
                        field[] = parsed_value
                    return success
                of `int_param_u64`:
                    let (parsed_value, success) = uint_from_string[uint64](value)
                    if success:
                        let field = cast[ptr uint64](cast[uint](address) + get_param_offset(name))
                        field[] = parsed_value
                    return success
                of `int_param_float`:
                    let (parsed_value, success) = float_from_string[float](value)
                    if success:
                        let field = cast[ptr float](cast[uint](address) + get_param_offset(name))
                        field[] = parsed_value
                    return success
                of `int_param_f32`:
                    let (parsed_value, success) = float_from_string[float32](value)
                    if success:
                        let field = cast[ptr float32](cast[uint](address) + get_param_offset(name))
                        field[] = parsed_value
                    return success
                of `int_param_f64`:
                    let (parsed_value, success) = float_from_string[float64](value)
                    if success:
                        let field = cast[ptr float64](cast[uint](address) + get_param_offset(name))
                        field[] = parsed_value
                    return success
                of `int_param_char`:
                    if value.len != 1: return false
                    let field = cast[ptr char](cast[uint](address) + get_param_offset(name))
                    field[] = value[0]
                    return true
                of `int_param_undefined`:
                    return false
                of `int_param_seq_string`:
                    let field = cast[ptr seq[string]](cast[uint](address) + get_param_offset(name))
                    field[].add value
                    return true
                of `int_param_seq_int`:
                    let (parsed_value, success) = int_from_string[int](value)
                    if success:
                        let field = cast[ptr seq[int]](cast[uint](address) + get_param_offset(name))
                        field[].add parsed_value
                    return success
                of `int_param_seq_float`:
                    let (parsed_value, success) = float_from_string[float](value)
                    if success:
                        let field = cast[ptr seq[float]](cast[uint](address) + get_param_offset(name))
                        field[].add parsed_value
                    return success
                else:
                    return false

            var
                awaiting_value = false
                awaiting_value_for = ""
                writing_to_seq = false
                writing_bare_seq = false
                current_seq_length = 0
                desired_seq_length = 0
                current_bare_index = 0
                no_await_value_check_until = 0
                force_bare = false

            if implicit_bare:
                var last_seq_string = -1
                var add_implicit_bare = true
                for i, kind in `outer_param_type`:
                    if kind == int_param_seq_string:
                        if i in `outer_bare_indexes`:
                            add_implicit_bare = false
                            break
                        else:
                            last_seq_string = i
                if add_implicit_bare and last_seq_string >= 0:
                    `outer_bare_indexes`.add(last_seq_string)

            when DEBUG:
                var words:seq[string] = parse_cmd_line(DEBUG_ARGS)
            else:
                var words:seq[string] = command_line_params()
            var next_word_index = 0
            while next_word_index < words.len:
                let word = words[next_word_index]
                next_word_index += 1
                if ((dash_denotes_param and word.starts_with("-")) or (slash_denotes_param and word.starts_with("/"))) and not force_bare:
                    if writing_to_seq:
                        if desired_seq_length != 0 and desired_seq_length != current_seq_length:
                            parse_error("Expected " & desired_seq_length.repr & " values for: " & get_prefix(awaiting_value_for) & awaiting_value_for)
                        writing_to_seq = false
                    elif awaiting_value and next_word_index > no_await_value_check_until:
                        parse_error("Expected value for: " & get_prefix(awaiting_value_for) & awaiting_value_for)

                    if dash_denotes_param and word == "--":
                        if double_dash_separator:
                            force_bare = true
                        continue

                    if split_on_colon and word.contains(":"):
                        var c = word.find(":")
                        words.insert(word[0 ..< c], next_word_index)
                        words.insert(word[c + 1 ..< ^0], next_word_index + 1)
                        continue
                    elif split_on_equals and word.contains("="):
                        var c = word.find("=")
                        words.insert(word[0 ..< c], next_word_index)
                        words.insert(word[c + 1 ..< ^0], next_word_index + 1)
                        continue

                    var name = word[1 ..< ^0].to_lower

                    if use_double_dash:
                        if name.starts_with("-"):
                            name = name[1 ..< ^0]
                        elif name.len > 1:
                            for i, letter in name.pairs:
                                words.insert "-" & letter, next_word_index + i
                            no_await_value_check_until = next_word_index + name.len + 1
                            continue

                    if name in `outer_alias_names`:
                        let index = `outer_alias_names`.find(name)
                        let name_index = `outer_alias_index`[index]
                        name = `outer_param_names`[name_index]

                    let found = `outer_param_names`.contains(name) and (not is_bare(name) or bare_can_still_be_named)
                    if not found:
                        if automatic_help and (name == "help" or name == "h" or name == "?"):
                            do_help()
                            quit(0)
                        else:
                            parse_error("No such parameter: " & word)
                    if parameters_are_unique and is_present(addr present, name):
                        parse_error("Parameter already set: " & word)

                    if get_param_type(name) == `int_param_bool`:
                        if set_value(addr options, name):
                            set_present(addr present, name)
                        else:
                            parse_error("Failed to set " & word & ": this should not happen!")
                    else:
                        awaiting_value = true
                        awaiting_value_for = name
                else:
                    if awaiting_value:
                        if set_value(addr options, awaiting_value_for, word):
                            set_present(addr present, awaiting_value_for)
                            if writing_to_seq:
                                current_seq_length += 1
                            else:
                                if is_seq(awaiting_value_for):
                                    writing_to_seq = true
                                    desired_seq_length = get_desired_seq_len(awaiting_value_for)
                                    current_seq_length = 1
                                else:
                                    awaiting_value = false
                            if writing_to_seq and desired_seq_length != 0 and current_seq_length >= desired_seq_length:
                                awaiting_value = false
                        else:
                            parse_error("Could not parse value for: " & word)
                    else:
                        var ok = false
                        while current_bare_index < `outer_bare_indexes`.len:
                            let index = `outer_bare_indexes`[current_bare_index]
                            let kind = `outer_param_type`[index]
                            writing_bare_seq = false
                            if can_parse_as(word, kind):
                                if kind == int_param_seq_string or kind == int_param_seq_int or kind == int_param_seq_float:
                                    if `outer_param_length`[index] == 0 or get_seq_len(addr options, `outer_param_names`[index], kind) < `outer_param_length`[index]:
                                        writing_bare_seq = true
                                        ok = true
                                        break
                                else:
                                    ok = true
                                    break
                            current_bare_index += 1
                        if not ok:
                            parse_error("Could not accept argument: " & word)
                        let bare_name = `outer_param_names`[`outer_bare_indexes`[current_bare_index]]
                        if set_value(addr options, bare_name, word):
                            set_present(addr present, bare_name)
                        else:
                            parse_error("Could not parse value for: " & word)
                        let kind = `outer_param_type`[`outer_bare_indexes`[current_bare_index]]
                        if kind != int_param_seq_string and kind != int_param_seq_int and kind != int_param_seq_float:
                            current_bare_index += 1

            if awaiting_value:
                if writing_to_seq:
                    if desired_seq_length != 0 and current_seq_length < desired_seq_length:
                        parse_error("Expected " & desired_seq_length.repr & " values for: " & get_prefix(awaiting_value_for) & awaiting_value_for)
                else:
                    parse_error("Expected value for: " & get_prefix(awaiting_value_for) & awaiting_value_for)
            elif writing_bare_seq:
                let index = `outer_bare_indexes`[current_bare_index]
                let kind = `outer_param_type`[index]
                let name = `outer_param_names`[index]
                desired_seq_length = `outer_param_length`[index]
                if desired_seq_length != 0 and get_seq_len(addr options, `outer_param_names`[index], kind) < desired_seq_length:
                    parse_error("Expected " & desired_seq_length.repr & " values for: " & get_prefix(name) & name)

            var missing = false
            for index in `outer_required_indexes`:
                let name = `outer_param_names`[index]
                if not is_present(addr present, name):
                    echo "Value required for: " & get_prefix(name) & name
                    missing = true
            if missing:
                parse_error("Missing required value(s).")

            return (options, present)


    var type_node = new_nim_node(nnk_type_section)
    var present_type_node = new_nim_node(nnk_type_section)
    var var_node = new_nim_node(nnk_var_section)
    var present_var_node = new_nim_node(nnk_var_section)
    var call_node = new_nim_node(nnk_call)
    var info_node = new_nim_node(nnk_var_section)

    result = new_nim_node(nnk_block_stmt)
    result.add new_empty_node()
    result.add new_nim_node(nnk_stmt_list)

    result[1].add type_node
    result[1].add present_type_node
    result[1].add var_node
    result[1].add present_var_node
    result[1].add param_names_node
    result[1].add param_node
    result[1].add param_present_node
    result[1].add param_type_node
    result[1].add info_node
    result[1].add param_alias_name_node
    result[1].add param_alias_index_node
    result[1].add param_default_node
    result[1].add param_len_node
    result[1].add param_description_node
    result[1].add param_required_node
    result[1].add bare_index_node
    result[1].add offset_node
    result[1].add proc_node
    result[1].add call_node

    type_node.add new_nim_node(nnk_type_def)
    type_node[0].add ident(TYPE_NAME)
    type_node[0].add new_empty_node()
    type_node[0].add new_nim_node(nnk_object_ty)
    type_node[0][2].add new_empty_node()
    type_node[0][2].add new_empty_node()
    type_node[0][2].add new_nim_node(nnk_rec_list)
    type_node = type_node[0][2][2]

    present_type_node.add new_nim_node(nnk_type_def)
    present_type_node[0].add ident(TYPE_PRESENT_NAME)
    present_type_node[0].add new_empty_node()
    present_type_node[0].add new_nim_node(nnk_object_ty)
    present_type_node[0][2].add new_empty_node()
    present_type_node[0][2].add new_empty_node()
    present_type_node[0][2].add new_nim_node(nnk_rec_list)
    present_type_node = present_type_node[0][2][2]

    var_node.add new_nim_node(nnk_ident_defs)
    var_node[0].add ident(VAR_NAME)
    var_node[0].add new_empty_node()
    var_node[0].add new_nim_node(nnk_obj_constr)
    var_node = var_node[0][2]

    present_var_node.add new_nim_node(nnk_ident_defs)
    present_var_node[0].add ident(VAR_PRESENT_NAME)
    present_var_node[0].add new_empty_node()
    present_var_node[0].add new_nim_node(nnk_call)
    present_var_node = present_var_node[0][2]

    var_node.add ident(TYPE_NAME)
    present_var_node.add ident(TYPE_PRESENT_NAME)

    offset_node = offset_node[1]

    call_node.add ident(PROC_NAME)
    call_node.add ident(VAR_NAME)
    call_node.add ident(VAR_PRESENT_NAME)


    template add_type(name: string, kind: ParamKind) =
        type_node.add(
            nnk_ident_defs.new_tree(
                ident(name),
                ident_from_kind(kind),
                new_empty_node()))
        present_type_node.add(
            nnk_ident_defs.new_tree(
                ident(name),
                ident("bool"),
                new_empty_node()))

    template add_var(name: string, value_node: Nim_Node) =
        if value_node != nil:
            var_node.add(
                nnk_expr_colon_expr.new_tree(
                    ident(name),
                    value_node.copy_nim_node))

    template add_offset(name: string) =
        offset_node.add(
            nnk_call.new_tree(
                nnk_dot_expr.new_tree(
                    ident(OFFSET_NAME),
                    ident("add")),
                nnk_infix.new_tree(
                    ident("-"),
                    nnk_cast.new_tree(
                        ident("uint"),
                        nnk_command.new_tree(
                            ident("addr"),
                            nnk_dot_expr.new_tree(
                                ident(VAR_NAME),
                                ident(name)))),
                    nnk_cast.new_tree(
                        ident("uint"),
                        nnk_command.new_tree(
                            ident("addr"),
                            ident(VAR_NAME))))))

    template add_present_offset(name: string) =
        offset_node.add(
            nnk_call.new_tree(
                nnk_dot_expr.new_tree(
                    ident(OFFSET_PRESENT_NAME),
                    ident("add")),
                nnk_infix.new_tree(
                    ident("-"),
                    nnk_cast.new_tree(
                        ident("uint"),
                        nnk_command.new_tree(
                            ident("addr"),
                            nnk_dot_expr.new_tree(
                                ident(VAR_PRESENT_NAME),
                                ident(name)))),
                    nnk_cast.new_tree(
                        ident("uint"),
                        nnk_command.new_tree(
                            ident("addr"),
                            ident(VAR_PRESENT_NAME))))))

    template add_name(name: string) =
        offset_node.add(
            nnk_call.new_tree(
                nnk_dot_expr.new_tree(
                    ident(OFFSET_NAMES_NAME),
                    ident("add")),
                new_str_lit_node(name)))

    template add_type_lookup(name: string, kind: Param_Kind) =
        offset_node.add(
            nnk_call.new_tree(
                nnk_dot_expr.new_tree(
                    ident(VAR_TYPE_NAME),
                    ident("add")),
                new_int_lit_node(int_param_from_param(kind))))

    template add_default_value(name: string, default: string) =
        offset_node.add(
            nnk_call.new_tree(
                nnk_dot_expr.new_tree(
                    ident(VAR_DEFAULT_NAME),
                    ident("add")),
                new_str_lit_node(default)))

    template add_seq_length(name: string, length: int) =
        offset_node.add(
            nnk_call.new_tree(
                nnk_dot_expr.new_tree(
                    ident(VAR_LEN_NAME),
                    ident("add")),
                new_int_lit_node(length)))

    template add_alias(name: string, index: int) =
        offset_node.add(
            nnk_call.new_tree(
                nnk_dot_expr.new_tree(
                    ident(VAR_ALIAS_NAME),
                    ident("add")),
                new_str_lit_node(name)))
        offset_node.add(
            nnk_call.new_tree(
                nnk_dot_expr.new_tree(
                    ident(VAR_ALIAS_INDEX),
                    ident("add")),
                new_int_lit_node(index)))

    template add_description(name: string, description: string) =
        offset_node.add(
            nnk_call.new_tree(
                nnk_dot_expr.new_tree(
                    ident(VAR_DESCRIPTION_NAME),
                    ident("add")),
                new_str_lit_node(description)))

    template add_bare_index(index: int) =
        offset_node.add(
            nnk_call.new_tree(
                nnk_dot_expr.new_tree(
                    ident(VAR_BARE_NAME),
                    ident("add")),
                new_int_lit_node(index)))

    template add_required(index: int) =
        offset_node.add(
            nnk_call.new_tree(
                nnk_dot_expr.new_tree(
                    ident(VAR_REQUIRED_NAME),
                    ident("add")),
                new_int_lit_node(index)))


    var alias_list:seq[string] = @[]
    let exe = current_source_path().extract_filename.change_file_ext("")
    info_node.add nnk_ident_defs.new_tree(
        ident(EXE_NAME),
        new_empty_node(),
        new_str_lit_node(exe)
    )

    for i, name in params_in_order.pairs:
        let param = params[name]
        add_type name, param.kind
        add_var name, value_node_from_param(param)
        add_offset name
        add_present_offset name
        add_name name
        add_type_lookup name, param.kind
        add_default_value name, string_from_param(param)
        add_seq_length name, param.seq_len
        add_description name, param.description
        if param.required:
            add_required(i)
        if param.accepts_bare:
            add_bare_index(i)
        for alias in param.alias:
            if alias in alias_list or alias in params:
                error("Parameter already exists: " & alias)
            add_alias alias, i
            alias_list.add alias


macro get_options*(body: untyped): untyped =
    ## Parses the command-line arguments provided by the user,
    ## using it and the code block to fill out an object's fields.
    ##
    ## Returns an object whose fields are detailed by the code block.
    ##
    ##
    ## All basic intrinsic types are supported:
    ## `string`, `char`, `bool`, `int`, `uint`, `float`
    ## (and all size variants: `int16`, `float32`, etc.)
    ##
    ## The block is written as if it were a `var`, i.e. all of these are valid:
    ## ```
    ## x = 0
    ## x:int32
    ## x:int = 20
    ## ```
    ## You may also use `seq[string]`, `seq[int]`, and `seq[float]` (though
    ## these may not be initialized to a default value: they must be empty)
    ## ```
    ## args: seq[string]
    ## ```
    ## If you do not explicitly specify a `{. bare .}` `seq[string]`, but do
    ## have one or more `seq[string]`, then the last one will be used to store
    ## all bare arguments.  (i.e. will be treated as if it had an implicit
    ## `{. bare .}` pragma.)
    ## This may be disabled with the `no_implicit_bare` setting.
    ##
    ##
    ## You may also add pragmas to the end of any line to modify parameter
    ## behaviour.  Each pragma has a more verbose alias, if you prefer that
    ## style of code.
    ##
    ## `{. info("text") .}` or `{. description("text") .}`
    ##   Description of the parameter shown in help text.
    ##
    ##
    ## `{. aka("a", "b", ...) .}` or `{. alias("a", "b", ...) .}`
    ##   Aliases for the parameter - user may use these as parameters;
    ##   they will write to the variable.
    ##
    ##
    ## `{. bare .}` or `{. positional .}`
    ##  Accepts a bare, positional argument (an argument which has not
    ##  been prefixed with a parameter name).  User will not be able to
    ##  refer to the argmuent with its parameter name.
    ##
    ##
    ## `{. need .}` or `.{ required .}`
    ##  Parameter must be supplied by user or an error is shown.
    ##
    ##
    ## `{. len(i) .}` or `.{ count(i) .}`
    ##  Place on a `seq` field to require that many values be supplied to it.
    ##  For example:
    ##  `position:seq[float] {. len(3) .} # x y z`
    ##
    ##
    ## *Example:*
    ## ```
    ## let options = get_options:
    ##     teenager = "Joe Random" {. alias("name", "n") .}
    ##     age[int8] = 13
    ##     nin:string              {. info("National Insurance Number") .}
    ##
    ## if options.nin.len != 9:
    ##     report "Must supply valid NIN"
    ##     quit(1)
    ##
    ## if options.age < 13 or options.age > 19:
    ##     report "Not a teenager!"
    ##     quit(1)
    ## ```
    var options, _ = quote do:
        get_options_and_supplied(`body`)[0]
    return options


when DEBUG:
    DEBUG_ARGS = "--age:2 there --big 10 --namu \"Joe Random\"  -x 1 10 20 30 -h -?"

    config: no_slash.dash_dash_parameters.value_after_colon.value_after_equals
    #command_name "simples"
    help_text "Nim module " & VERSION

    var (options, is_set) = get_options_and_supplied:
        name = "Default Name" {. alias("n", "namu") .}
        toggle = false {. info("Flip me") .}
        letter = 'a' {. bare, info("Initial") .}
        age = 1 {. info("How old they are") .}
        here = true {. alias("h"), info("And now!") .}
        there = false  {. info("And back!") .}
        big:float64 = 1.1
        small:float = 2.2
        flat:uint = 2
        hello:string  {. need, bare .}
        x:int {. required .}
        position:seq[int] {. len(3), bare .}
        args: seq[string]


    prettify("Options", options, true)
    prettify("Supplied", is_set)
